### ISSUE TITLE
using convertToExcalidrawElements to convert text  ExcalidrawElementSkeleton to ExcalidrawElement, the baseline property is not response to the fontsize

### ISSUE THREAD

**Issue by welentsai** [yubinTW/excali-tool#1]
using convertToExcalidrawElements to convert text  ExcalidrawElementSkeleton to ExcalidrawElement

for example,
```
const myElements = convertToExcalidrawElements([
    {
      type: 'text',
      x: 100,
      y: 100,
      text: 'HELLO WORLD!!',
      fontSize: 25
    }
  ])
```
the converted `baseline` property of ExcalidrawElement is not the same as using Excalidraw library

**Comment by yubinTW** [comment]
Because `jsdom` cannot measure the offsetHeight of the DOM. [ref](https://github.com/jsdom/jsdom/blob/main/lib/jsdom/living/nodes/HTMLElement-impl.js#L199)

I calc the baseline by [multiplying a constant ratio](https://github.com/yubinTW/excali-tool/commit/1969bfd0088dcedb256707fac2bf8eea0d5c102c). 

Release in `0.0.6`
